version: "3"
services:
    minimalci:
        build: .
        volumes:
            - /srv/minimalci:/server/data
            - /srv/minimalci/ssh:/root/.ssh:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 80:8000
        environment:
            - REPO_NAME=minimalci
            - REPO_URL=git@github.com:oysols/minimalci.git
            - BASE_URL=http://35.227.107.72/

            - ADDITIONAL_MOUNTS=/srv/minimalci/secrets:/secrets:ro

            # Optional
            - TASKS_FILE=tasks.py
            - GITHUB_CLIENT_ID
            - GITHUB_CLIENT_SECRET
            - GITHUB_AUTHORIZED_USERS  # user1,user2,user3

            - ISOLATE_PYTHON=true  # Only required for running minimalci on itself

        restart: always
